transports:tcp: Remove loop parameter from open_connection
TypeError: BaseEventLoop.create_connection() got an unexpected keyword
argument 'loop'

The loop parameter in open_connection has been removed in Python 3.10. It's
now passed on to BaseEventLoop.create_connection() which gives the above
error.

Signed-off-by: Robin van der Gracht <robin@protonic.nl>